package com.csaba79coder.apifirstdevelopment.value;

public enum Genre {
    DETECTIVE_FICTION, NOVEL, MYSTERY, THRILLER, HORROR, HISTORICAL, ROMANCE, WESTERN, BILDUNGSROMAN,
    SCIENCE_FICTION, FICTION, FANTASY, MAGICAL_REALISM, REALIST_LITERATURE, OTHER
}
